import { GlobalAddressKeyField, getAltKey, iterateGlobalAddresskeyFields } from './global-address-key';

type Case = {
  address: string;
  globalAddressKey: string;
  expectedFields: GlobalAddressKeyField[];
  expectedAltKey: string | null;
};

const cases: Case[] = [
  {
    address: '12 High Street, ARMIDALE  NSW 2350',
    globalAddressKey: 'aWQ9MTIgSGlnaCBTdHJlZXQsIEFSTUlEQUxFICBOU1cgMjM1MCwgQXVzdHJhbGlhfmFsdF9rZXk9R0FOU1c3MDY2NTA5NTZ-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwNE9BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQUVGVDRVQUFoQUE0QUFBQUFBQUFBQUFELi4xQUFBQUFBLi4uLi53QUFBQUFBQUFBQUFBQUFBQUFBQURFeUlFaHBaMmdnVXlCTlpXeGlBQUFBQUFBLSQkJA',
    expectedFields: [
      ['id', '12 High Street, ARMIDALE  NSW 2350, Australia'],
      ['alt_key', 'GANSW706650956'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.7304OAUEHALnBwAAAAAIAgEAAAAAEFT4UAAhAA4AAAAAAAAAAAD..1AAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW706650956',
  },
  {
    address: '12 High Street, BALMAIN  NSW 2041',
    globalAddressKey: 'aWQ9MTIgSGlnaCBTdHJlZXQsIEJBTE1BSU4gIE5TVyAyMDQxLCBBdXN0cmFsaWF-YWx0X2tleT1HQU5TVzcxMDUzMzAzOH5kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzBrT0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBRmFNTTBBQWhBQTRBQUFBQUFBQUFBQUQuLjFBQUFBQUEuLi4uLndBQUFBQUFBQUFBQUFBQUFBQUFBREV5SUVocFoyZ2dVeUJOWld4aUFBQUFBQUEtJCQk',
    expectedFields: [
      ['id', '12 High Street, BALMAIN  NSW 2041, Australia'],
      ['alt_key', 'GANSW710533038'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730kOAUEHALnBwAAAAAIAgEAAAAAFaMM0AAhAA4AAAAAAAAAAAD..1AAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW710533038',
  },
  {
    address: '12 High Street, BANKSTOWN  NSW 2200',
    globalAddressKey: 'aWQ9MTIgSGlnaCBTdHJlZXQsIEJBTktTVE9XTiAgTlNXIDIyMDAsIEF1c3RyYWxpYX5hbHRfa2V5PUdBTlNXNzA0MDA0OTAxfmRhdGFzZXQ9QVVTX0RBVEFGVVNJT05-Zm9ybWF0X2tleT1BVVMkZGF0YWZ1c2lvbiQ3LjczMG5PQVVFSEFMbkJ3QUFBQUFJQWdFQUFBQUFGdEZlRUFBaEFBNEFBQUFBQUFBQUFBRC4uMUFBQUFBQS4uLi4ud0FBQUFBQUFBQUFBQUFBQUFBQUFERXlJRWhwWjJnZ1V5Qk5aV3hpQUFBQUFBQS0kJCQ',
    expectedFields: [
      ['id', '12 High Street, BANKSTOWN  NSW 2200, Australia'],
      ['alt_key', 'GANSW704004901'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730nOAUEHALnBwAAAAAIAgEAAAAAFtFeEAAhAA4AAAAAAAAAAAD..1AAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW704004901',
  },
  {
    address: '12 High Street, BARNSLEY  NSW 2278',
    globalAddressKey: 'aWQ9MTIgSGlnaCBTdHJlZXQsIEJBUk5TTEVZICBOU1cgMjI3OCwgQXVzdHJhbGlhfmFsdF9rZXk9R0FOU1c3MDQwMjQzNjB-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwY09BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQUdISGJrQUFoQUE0QUFBQUFBQUFBQUFELi4xQUFBQUFBLi4uLi53QUFBQUFBQUFBQUFBQUFBQUFBQURFeUlFaHBaMmdnVXlCTlpXeGlBQUFBQUFBLSQkJA',
    expectedFields: [
      ['id', '12 High Street, BARNSLEY  NSW 2278, Australia'],
      ['alt_key', 'GANSW704024360'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730cOAUEHALnBwAAAAAIAgEAAAAAGHHbkAAhAA4AAAAAAAAAAAD..1AAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW704024360',
  },
  {
    address: '12 High Street, BATEMANS BAY  NSW 2536',
    globalAddressKey: 'aWQ9MTIgSGlnaCBTdHJlZXQsIEJBVEVNQU5TIEJBWSAgTlNXIDI1MzYsIEF1c3RyYWxpYX5hbHRfa2V5PUdBTlNXNzA0MDQ0NTc4fmRhdGFzZXQ9QVVTX0RBVEFGVVNJT05-Zm9ybWF0X2tleT1BVVMkZGF0YWZ1c2lvbiQ3LjczMEhPQVVFSEFMbkJ3QUFBQUFJQWdFQUFBQUFHWHp2VUFBaEFBNEFBQUFBQUFBQUFBRC4uMUFBQUFBQS4uLi4ud0FBQUFBQUFBQUFBQUFBQUFBQUFERXlJRWhwWjJnZ1V5Qk5aV3hpQUFBQUFBQS0kJCQ',
    expectedFields: [
      ['id', '12 High Street, BATEMANS BAY  NSW 2536, Australia'],
      ['alt_key', 'GANSW704044578'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730HOAUEHALnBwAAAAAIAgEAAAAAGXzvUAAhAA4AAAAAAAAAAAD..1AAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW704044578',
  },
  {
    address: '12 High Street, BEGA  NSW 2550',
    globalAddressKey: 'aWQ9MTIgSGlnaCBTdHJlZXQsIEJFR0EgIE5TVyAyNTUwLCBBdXN0cmFsaWF-YWx0X2tleT1HQU5TVzcwNDA2ODEyNH5kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzByT0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBRzRpejBBQWhBQTRBQUFBQUFBQUFBQUQuLjFBQUFBQUEuLi4uLndBQUFBQUFBQUFBQUFBQUFBQUFBREV5SUVocFoyZ2dVeUJOWld4aUFBQUFBQUEtJCQk',
    expectedFields: [
      ['id', '12 High Street, BEGA  NSW 2550, Australia'],
      ['alt_key', 'GANSW704068124'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730rOAUEHALnBwAAAAAIAgEAAAAAG4iz0AAhAA4AAAAAAAAAAAD..1AAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW704068124',
  },
  {
    address: '12 High Street, BELMONT  NSW 2280',
    globalAddressKey: 'aWQ9MTIgSGlnaCBTdHJlZXQsIEJFTE1PTlQgIE5TVyAyMjgwLCBBdXN0cmFsaWF-YWx0X2tleT1HQU5TVzcxMTgyNjQwNX5kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzAxT0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBSE1SVTBBQWhBQTRBQUFBQUFBQUFBQUQuLjFBQUFBQUEuLi4uLndBQUFBQUFBQUFBQUFBQUFBQUFBREV5SUVocFoyZ2dVeUJOWld4aUFBQUFBQUEtJCQk',
    expectedFields: [
      ['id', '12 High Street, BELMONT  NSW 2280, Australia'],
      ['alt_key', 'GANSW711826405'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.7301OAUEHALnBwAAAAAIAgEAAAAAHMRU0AAhAA4AAAAAAAAAAAD..1AAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW711826405',
  },
  {
    address: '12 High Street, BLACK HEAD  NSW 2430',
    globalAddressKey: 'aWQ9MTIgSGlnaCBTdHJlZXQsIEJMQUNLIEhFQUQgIE5TVyAyNDMwLCBBdXN0cmFsaWF-YWx0X2tleT1HQU5TVzcxNTIzODI1OX5kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzAyT0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBSVBSZEVBQWhBQTRBQUFBQUFBQUFBQUQuLjFBQUFBQUEuLi4uLndBQUFBQUFBQUFBQUFBQUFBQUFBREV5SUVocFoyZ2dVeUJOWld4aUFBQUFBQUEtJCQk',
    expectedFields: [
      ['id', '12 High Street, BLACK HEAD  NSW 2430, Australia'],
      ['alt_key', 'GANSW715238259'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.7302OAUEHALnBwAAAAAIAgEAAAAAIPRdEAAhAA4AAAAAAAAAAAD..1AAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW715238259',
  },
  {
    address: '12 High Street, ARDGLEN  NSW 2338',
    globalAddressKey: 'aWQ9MTIgSGlnaCBTdHJlZXQsIEFSREdMRU4gIE5TVyAyMzM4LCBBdXN0cmFsaWF-YWx0X2tleT1HQU5TVzcxODg0NDQzNn5kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzB5T0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBRDdhaEFBQUFBQUFBQURFeUFBRC4uMUFBQUFBQS4uLi4ud0FBQUFBQUFBQUFBQUFBQUFBQUFERXlJRWhwWjJnZ1V5Qk5aV3hpQUFBQUFBQS0kJCQ',
    expectedFields: [
      ['id', '12 High Street, ARDGLEN  NSW 2338, Australia'],
      ['alt_key', 'GANSW718844436'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730yOAUEHALnBwAAAAAIAgEAAAAAD7ahAAAAAAAAADEyAAD..1AAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW718844436',
  },
  {
    address: 'Unit 1  12 High Street, BATEMANS BAY  NSW 2536',
    globalAddressKey: 'aWQ9VW5pdCAxICAxMiBIaWdoIFN0cmVldCwgQkFURU1BTlMgQkFZICBOU1cgMjUzNiwgQXVzdHJhbGlhfmFsdF9rZXk9R0FOU1c3MDQwMzk3MjZ-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwWU9BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQUdYenkwQmdoQVlvUUVDRUFnZ0FBQUFBQUFBQUFBUC4uVUFBQUFBRC4uLi4uQUFBQUFBQUFBQUFBQUFBQUFBQUFNVElnU0dsbmFDQlRJRTFsYkdJQUFBQUFBQS0tJCQk',
    expectedFields: [
      ['id', 'Unit 1  12 High Street, BATEMANS BAY  NSW 2536, Australia'],
      ['alt_key', 'GANSW704039726'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730YOAUEHALnBwAAAAAIAgEAAAAAGXzy0BghAYoQECEAggAAAAAAAAAAAP..UAAAAAD.....AAAAAAAAAAAAAAAAAAAAMTIgSGlnaCBTIE1lbGIAAAAAAA--$$$'],
    ],
    expectedAltKey: 'GANSW704039726',
  },
  {
    address: 'Unit 1  12 High Street, BLACK HEAD  NSW 2430',
    globalAddressKey: 'aWQ9VW5pdCAxICAxMiBIaWdoIFN0cmVldCwgQkxBQ0sgSEVBRCAgTlNXIDI0MzAsIEF1c3RyYWxpYX5hbHRfa2V5PUdBTlNXNzA2NTYwNDU0fmRhdGFzZXQ9QVVTX0RBVEFGVVNJT05-Zm9ybWF0X2tleT1BVVMkZGF0YWZ1c2lvbiQ3LjczMHlPQVVFSEFMbkJ3QUFBQUFJQWdFQUFBQUFJUFJna0JnaEFZb1FFQ0VBZ2dBQUFBQUFBQUFBQVAuLlVBQUFBQUQuLi4uLkFBQUFBQUFBQUFBQUFBQUFBQUFBTVRJZ1NHbG5hQ0JUSUUxbGJHSUFBQUFBQUEtLSQkJA',
    expectedFields: [
      ['id', 'Unit 1  12 High Street, BLACK HEAD  NSW 2430, Australia'],
      ['alt_key', 'GANSW706560454'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730yOAUEHALnBwAAAAAIAgEAAAAAIPRgkBghAYoQECEAggAAAAAAAAAAAP..UAAAAAD.....AAAAAAAAAAAAAAAAAAAAMTIgSGlnaCBTIE1lbGIAAAAAAA--$$$'],
    ],
    expectedAltKey: 'GANSW706560454',
  },
  {
    address: 'Unit 2  12 High Street, BATEMANS BAY  NSW 2536',
    globalAddressKey: 'aWQ9VW5pdCAyICAxMiBIaWdoIFN0cmVldCwgQkFURU1BTlMgQkFZICBOU1cgMjUzNiwgQXVzdHJhbGlhfmFsdF9rZXk9R0FOU1c3MDQwNDE1NTN-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwRE9BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQUdYejFVQmdoQVlvUUVDRUFnZ0FBQUFBQUFBQUFBUC4uVUFBQUFBRC4uLi4uQUFBQUFBQUFBQUFBQUFBQUFBQUFNVElnU0dsbmFDQlRJRTFsYkdJQUFBQUFBQS0tJCQk',
    expectedFields: [
      ['id', 'Unit 2  12 High Street, BATEMANS BAY  NSW 2536, Australia'],
      ['alt_key', 'GANSW704041553'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730DOAUEHALnBwAAAAAIAgEAAAAAGXz1UBghAYoQECEAggAAAAAAAAAAAP..UAAAAAD.....AAAAAAAAAAAAAAAAAAAAMTIgSGlnaCBTIE1lbGIAAAAAAA--$$$'],
    ],
    expectedAltKey: 'GANSW704041553',
  },
  {
    address: 'Unit 2  12 High Street, BLACK HEAD  NSW 2430',
    globalAddressKey: 'aWQ9VW5pdCAyICAxMiBIaWdoIFN0cmVldCwgQkxBQ0sgSEVBRCAgTlNXIDI0MzAsIEF1c3RyYWxpYX5hbHRfa2V5PUdBTlNXNzA2NTYwNDUzfmRhdGFzZXQ9QVVTX0RBVEFGVVNJT05-Zm9ybWF0X2tleT1BVVMkZGF0YWZ1c2lvbiQ3LjczMHJPQVVFSEFMbkJ3QUFBQUFJQWdFQUFBQUFJUFJqRUJnaEFZb1FFQ0VBZ2dBQUFBQUFBQUFBQVAuLlVBQUFBQUQuLi4uLkFBQUFBQUFBQUFBQUFBQUFBQUFBTVRJZ1NHbG5hQ0JUSUUxbGJHSUFBQUFBQUEtLSQkJA',
    expectedFields: [
      ['id', 'Unit 2  12 High Street, BLACK HEAD  NSW 2430, Australia'],
      ['alt_key', 'GANSW706560453'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730rOAUEHALnBwAAAAAIAgEAAAAAIPRjEBghAYoQECEAggAAAAAAAAAAAP..UAAAAAD.....AAAAAAAAAAAAAAAAAAAAMTIgSGlnaCBTIE1lbGIAAAAAAA--$$$'],
    ],
    expectedAltKey: 'GANSW706560453',
  },
  {
    address: 'Unit 3  12 High Street, BATEMANS BAY  NSW 2536',
    globalAddressKey: 'aWQ9VW5pdCAzICAxMiBIaWdoIFN0cmVldCwgQkFURU1BTlMgQkFZICBOU1cgMjUzNiwgQXVzdHJhbGlhfmFsdF9rZXk9R0FOU1c3MDQwNDE1NTR-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwY09BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQUdYejMwQmdoQVlvUUVDRUFnZ0FBQUFBQUFBQUFBUC4uVUFBQUFBRC4uLi4uQUFBQUFBQUFBQUFBQUFBQUFBQUFNVElnU0dsbmFDQlRJRTFsYkdJQUFBQUFBQS0tJCQk',
    expectedFields: [
      ['id', 'Unit 3  12 High Street, BATEMANS BAY  NSW 2536, Australia'],
      ['alt_key', 'GANSW704041554'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730cOAUEHALnBwAAAAAIAgEAAAAAGXz30BghAYoQECEAggAAAAAAAAAAAP..UAAAAAD.....AAAAAAAAAAAAAAAAAAAAMTIgSGlnaCBTIE1lbGIAAAAAAA--$$$'],
    ],
    expectedAltKey: 'GANSW704041554',
  },
  {
    address: 'Unit 3  12 High Street, BLACK HEAD  NSW 2430',
    globalAddressKey: 'aWQ9VW5pdCAzICAxMiBIaWdoIFN0cmVldCwgQkxBQ0sgSEVBRCAgTlNXIDI0MzAsIEF1c3RyYWxpYX5hbHRfa2V5PUdBTlNXNzA2NTYwNDUyfmRhdGFzZXQ9QVVTX0RBVEFGVVNJT05-Zm9ybWF0X2tleT1BVVMkZGF0YWZ1c2lvbiQ3LjczMG9PQVVFSEFMbkJ3QUFBQUFJQWdFQUFBQUFJUFJsa0JnaEFZb1FFQ0VBZ2dBQUFBQUFBQUFBQVAuLlVBQUFBQUQuLi4uLkFBQUFBQUFBQUFBQUFBQUFBQUFBTVRJZ1NHbG5hQ0JUSUUxbGJHSUFBQUFBQUEtLSQkJA',
    expectedFields: [
      ['id', 'Unit 3  12 High Street, BLACK HEAD  NSW 2430, Australia'],
      ['alt_key', 'GANSW706560452'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730oOAUEHALnBwAAAAAIAgEAAAAAIPRlkBghAYoQECEAggAAAAAAAAAAAP..UAAAAAD.....AAAAAAAAAAAAAAAAAAAAMTIgSGlnaCBTIE1lbGIAAAAAAA--$$$'],
    ],
    expectedAltKey: 'GANSW706560452',
  },
  {
    address: 'Unit 4  12 High Street, BATEMANS BAY  NSW 2536',
    globalAddressKey: 'aWQ9VW5pdCA0ICAxMiBIaWdoIFN0cmVldCwgQkFURU1BTlMgQkFZICBOU1cgMjUzNiwgQXVzdHJhbGlhfmFsdF9rZXk9R0FOU1c3MDQwNDE1NTV-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwNk9BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQUdYejZVQmdoQVlvUUVDRUFnZ0FBQUFBQUFBQUFBUC4uVUFBQUFBRC4uLi4uQUFBQUFBQUFBQUFBQUFBQUFBQUFNVElnU0dsbmFDQlRJRTFsYkdJQUFBQUFBQS0tJCQk',
    expectedFields: [
      ['id', 'Unit 4  12 High Street, BATEMANS BAY  NSW 2536, Australia'],
      ['alt_key', 'GANSW704041555'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.7306OAUEHALnBwAAAAAIAgEAAAAAGXz6UBghAYoQECEAggAAAAAAAAAAAP..UAAAAAD.....AAAAAAAAAAAAAAAAAAAAMTIgSGlnaCBTIE1lbGIAAAAAAA--$$$'],
    ],
    expectedAltKey: 'GANSW704041555',
  },
  {
    address: 'Unit 5  12 High Street, BATEMANS BAY  NSW 2536',
    globalAddressKey: 'aWQ9VW5pdCA1ICAxMiBIaWdoIFN0cmVldCwgQkFURU1BTlMgQkFZICBOU1cgMjUzNiwgQXVzdHJhbGlhfmFsdF9rZXk9R0FOU1c3MDQwNDE1NTZ-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwR09BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQUdYejgwQmdoQVlvUUVDRUFnZ0FBQUFBQUFBQUFBUC4uVUFBQUFBRC4uLi4uQUFBQUFBQUFBQUFBQUFBQUFBQUFNVElnU0dsbmFDQlRJRTFsYkdJQUFBQUFBQS0tJCQk',
    expectedFields: [
      ['id', 'Unit 5  12 High Street, BATEMANS BAY  NSW 2536, Australia'],
      ['alt_key', 'GANSW704041556'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730GOAUEHALnBwAAAAAIAgEAAAAAGXz80BghAYoQECEAggAAAAAAAAAAAP..UAAAAAD.....AAAAAAAAAAAAAAAAAAAAMTIgSGlnaCBTIE1lbGIAAAAAAA--$$$'],
    ],
    expectedAltKey: 'GANSW704041556',
  },
  {
    address: 'Unit 6  12 High Street, BATEMANS BAY  NSW 2536',
    globalAddressKey: 'aWQ9VW5pdCA2ICAxMiBIaWdoIFN0cmVldCwgQkFURU1BTlMgQkFZICBOU1cgMjUzNiwgQXVzdHJhbGlhfmFsdF9rZXk9R0FOU1c3MTY5NTcyNjd-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwOU9BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQUdYei5VQmdoQVlvUUVDRUFnZ0FBQUFBQUFBQUFBUC4uVUFBQUFBRC4uLi4uQUFBQUFBQUFBQUFBQUFBQUFBQUFNVElnU0dsbmFDQlRJRTFsYkdJQUFBQUFBQS0tJCQk',
    expectedFields: [
      ['id', 'Unit 6  12 High Street, BATEMANS BAY  NSW 2536, Australia'],
      ['alt_key', 'GANSW716957267'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.7309OAUEHALnBwAAAAAIAgEAAAAAGXz.UBghAYoQECEAggAAAAAAAAAAAP..UAAAAAD.....AAAAAAAAAAAAAAAAAAAAMTIgSGlnaCBTIE1lbGIAAAAAAA--$$$'],
    ],
    expectedAltKey: 'GANSW716957267',
  },
  {
    address: '12 High Valley Place, BELROSE  NSW 2085',
    globalAddressKey: 'aWQ9MTIgSGlnaCBWYWxsZXkgUGxhY2UsIEJFTFJPU0UgIE5TVyAyMDg1LCBBdXN0cmFsaWF-YWx0X2tleT1HQU5TVzcxNjc1NDc4N35kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzBST0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBSFlOTDBBQWhBQTRBQUFBQUFBQUFBQUQuLjFBQUFBQUEuLi4uLndBQUFBQUFBQUFBQUFBQUFBQUFBREV5SUVocFoyZ2dVeUJOWld4aUFBQUFBQUEtJCQk',
    expectedFields: [
      ['id', '12 High Valley Place, BELROSE  NSW 2085, Australia'],
      ['alt_key', 'GANSW716754787'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730ROAUEHALnBwAAAAAIAgEAAAAAHYNL0AAhAA4AAAAAAAAAAAD..1AAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW716754787',
  },
  {
    address: '12 The High Road, BLAXLAND  NSW 2774',
    globalAddressKey: 'aWQ9MTIgVGhlIEhpZ2ggUm9hZCwgQkxBWExBTkQgIE5TVyAyNzc0LCBBdXN0cmFsaWF-YWx0X2tleT1HQU5TVzcxNjk0MDg5Nn5kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzBPT0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBSWl4dUVBQWhBQTRBQUFBQUFBQUFBQUQuLjFBQUFBQUEuLi4uLndBQUFBQUFBQUFBQUFBQUFBQUFBREV5SUVocFoyZ2dVeUJOWld4aUFBQUFBQUEtJCQk',
    expectedFields: [
      ['id', '12 The High Road, BLAXLAND  NSW 2774, Australia'],
      ['alt_key', 'GANSW716940896'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730OOAUEHALnBwAAAAAIAgEAAAAAIixuEAAhAA4AAAAAAAAAAAD..1AAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW716940896',
  },
  {
    address: '9-13 High Street, BOMBALA  NSW 2632',
    globalAddressKey: 'aWQ9OS0xMyBIaWdoIFN0cmVldCwgQk9NQkFMQSAgTlNXIDI2MzIsIEF1c3RyYWxpYX5hbHRfa2V5PUdBTlNXNzE3MzM0MjYxfmRhdGFzZXQ9QVVTX0RBVEFGVVNJT05-Zm9ybWF0X2tleT1BVVMkZGF0YWZ1c2lvbiQ3LjczMG9PQVVFSEFMbkJ3QUFBQUFJQWdFQUFBQUFJNDg0VUFEZ0FBQUFBQUFBQUFELi4wWUFBQUFBLi4uLi53QUFBQUFBQUFBQUFBQUFBQUFBQURFeUlFaHBaMmdnVXlCTlpXeGlBQUFBQUFBLSQkJA',
    expectedFields: [
      ['id', '9-13 High Street, BOMBALA  NSW 2632, Australia'],
      ['alt_key', 'GANSW717334261'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730oOAUEHALnBwAAAAAIAgEAAAAAI484UADgAAAAAAAAAAD..0YAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW717334261',
  },
  {
    address: '9-27 High Street, BOURKE  NSW 2840',
    globalAddressKey: 'aWQ9OS0yNyBIaWdoIFN0cmVldCwgQk9VUktFICBOU1cgMjg0MCwgQXVzdHJhbGlhfmFsdF9rZXk9R0FOU1c3MTgxOTYyMjh-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwV09BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQUp0Z3YwQURnQUFBQUFBQUFBQUQuLjBZQUFBQUEuLi4uLndBQUFBQUFBQUFBQUFBQUFBQUFBREV5SUVocFoyZ2dVeUJOWld4aUFBQUFBQUEtJCQk',
    expectedFields: [
      ['id', '9-27 High Street, BOURKE  NSW 2840, Australia'],
      ['alt_key', 'GANSW718196228'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730WOAUEHALnBwAAAAAIAgEAAAAAJtgv0ADgAAAAAAAAAAD..0YAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW718196228',
  },
  {
    address: 'Unit 1  2a High Street, ALSTONVILLE  NSW 2477',
    globalAddressKey: 'aWQ9VW5pdCAxICAyYSBIaWdoIFN0cmVldCwgQUxTVE9OVklMTEUgIE5TVyAyNDc3LCBBdXN0cmFsaWF-YWx0X2tleT1HQU5TVzcwNzc4NzE2Mn5kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzBjT0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBRHRPd0VCZ2hBWW9RRUNFQWdoQUFJUUFPQUFBQUFBQUFBQUFBLi45R0FBQUFBUC4uLi44QUFBQUFBQUFBQUFBQUFBQUFBQUF4TWlCSWFXZG9JRk1nVFdWc1lnQUFBQUFBJCQk',
    expectedFields: [
      ['id', 'Unit 1  2a High Street, ALSTONVILLE  NSW 2477, Australia'],
      ['alt_key', 'GANSW707787162'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730cOAUEHALnBwAAAAAIAgEAAAAADtOwEBghAYoQECEAghAAIQAOAAAAAAAAAAAA..9GAAAAAP....8AAAAAAAAAAAAAAAAAAAAxMiBIaWdoIFMgTWVsYgAAAAAA$$$'],
    ],
    expectedAltKey: 'GANSW707787162',
  },
  {
    address: 'The Peak, Unit 12  11 High Street, BATEMANS BAY  NSW 2536',
    globalAddressKey: 'aWQ9VGhlIFBlYWssIFVuaXQgMTIgIDExIEhpZ2ggU3RyZWV0LCBCQVRFTUFOUyBCQVkgIE5TVyAyNTM2LCBBdXN0cmFsaWF-YWx0X2tleT1HQU5TVzcwNDA0Mzc3MX5kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzBTT0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBR1h6VWtCZ2hBWW9RRUNFQWdoQUFJUUFPRUFFZ0FBQUFBQUFBQUFELi4wWUFBQUFBLi4uLi53QUFBQUFBQUFBQUFBQUFBQUFBQURFeUlFaHBaMmdnVXlCTlpXeGlBQUFBQUFBLSQkJA',
    expectedFields: [
      ['id', 'The Peak, Unit 12  11 High Street, BATEMANS BAY  NSW 2536, Australia'],
      ['alt_key', 'GANSW704043771'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730SOAUEHALnBwAAAAAIAgEAAAAAGXzUkBghAYoQECEAghAAIQAOEAEgAAAAAAAAAAD..0YAAAAA.....wAAAAAAAAAAAAAAAAAAADEyIEhpZ2ggUyBNZWxiAAAAAAA-$$$'],
    ],
    expectedAltKey: 'GANSW704043771',
  },
  {
    address: 'Unit 12  20 High Street, BLACK HEAD  NSW 2430',
    globalAddressKey: 'aWQ9VW5pdCAxMiAgMjAgSGlnaCBTdHJlZXQsIEJMQUNLIEhFQUQgIE5TVyAyNDMwLCBBdXN0cmFsaWF-YWx0X2tleT1HQU5TVzcxNjgwMDA4NH5kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzBPT0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBSVBTWEVCZ2hBWW9RRUNFQWdoQUFJUUFPQUFBQUFBQUFBQUFBLi45R0FBQUFBUC4uLi44QUFBQUFBQUFBQUFBQUFBQUFBQUF4TWlCSWFXZG9JRk1nVFdWc1lnQUFBQUFBJCQk',
    expectedFields: [
      ['id', 'Unit 12  20 High Street, BLACK HEAD  NSW 2430, Australia'],
      ['alt_key', 'GANSW716800084'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730OOAUEHALnBwAAAAAIAgEAAAAAIPSXEBghAYoQECEAghAAIQAOAAAAAAAAAAAA..9GAAAAAP....8AAAAAAAAAAAAAAAAAAAAxMiBIaWdoIFMgTWVsYgAAAAAA$$$'],
    ],
    expectedAltKey: 'GANSW716800084',
  },
  {
    address: '2 11 King Street, GLENELG NORTH  SA 5045',
    globalAddressKey: 'aWQ9MiAxMSBLaW5nIFN0cmVldCwgR0xFTkVMRyBOT1JUSCAgU0EgNTA0NSwgQXVzdHJhbGlhfmFsdF9rZXk9R0FTQV80MTYwMjMxMTV-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwQ09BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQnNNYnlFQUFoQUE0QUFBQUFBQUVBTWdBQUFQLi5NZ0FBQUFELi4uLi5BQUFBQUFBQUFBQUFBQUFBQUFBQU1pOHlNaUJMYVc1bklGTjBJRUZrWld3QUFBQUFBQS0tJCQk',
    expectedFields: [
      ['id', '2 11 King Street, GLENELG NORTH  SA 5045, Australia'],
      ['alt_key', 'GASA_416023115'],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730COAUEHALnBwAAAAAIAgEAAAABsMbyEAAhAA4AAAAAAAEAMgAAAP..MgAAAAD.....AAAAAAAAAAAAAAAAAAAAMi8yMiBLaW5nIFN0IEFkZWwAAAAAAA--$$$'],
    ],
    expectedAltKey: 'GASA_416023115',
  },
  // Addresses with no alt key.
  {
    address: 'Shop 31  918 Hay Street, PERTH  WA 6000',
    globalAddressKey: 'aWQ9U2hvcCAzMSAgOTE4IEhheSBTdHJlZXQsIFBFUlRIICBXQSA2MDAwLCBBdXN0cmFsaWF-YWx0X2tleT1-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwZk9BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQzVncWtrQkFoQUlJUUFDQUFBQUFBQUFBek1RQUEuLjlkQUFBQUFQLi4uLjhBQUFBQUFBQUFBQUFBQUFBQUFBQXpNU0JJWVhrZ1UzUWdVR1Z5QUFBQUFBQS0kJCQ',
    expectedFields: [
      ['id', 'Shop 31  918 Hay Street, PERTH  WA 6000, Australia'],
      ['alt_key', ''],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730fOAUEHALnBwAAAAAIAgEAAAAC5gqkkBAhAIIQACAAAAAAAAAzMQAA..9dAAAAAP....8AAAAAAAAAAAAAAAAAAAAzMSBIYXkgU3QgUGVyAAAAAAA-$$$'],
    ],
    expectedAltKey: null,
  },
  {
    address: 'Melbourne Central, Kiosk 2, Ground Floor  300 Lonsdale Street, MELBOURNE  VIC 3000',
    globalAddressKey: 'aWQ9TWVsYm91cm5lIENlbnRyYWwsIEtpb3NrIDIsIEdyb3VuZCBGbG9vciAgMzAwIExvbnNkYWxlIFN0cmVldCwgTUVMQk9VUk5FICBWSUMgMzAwMCwgQXVzdHJhbGlhfmFsdF9rZXk9fmRhdGFzZXQ9QVVTX0RBVEFGVVNJT05-Zm9ybWF0X2tleT1BVVMkZGF0YWZ1c2lvbiQ3LjczMFZPQVVFSEFMbkJ3QUFBQUFJQWdFQUFBQUNXeUpBa0JnaEFRSVFDQ0FBQUFBQUFBQUFBUC4uWkFBQUFBRC4uLi4uQUFBQUFBQUFBQUFBQUFBQUFBQUFURzl1YzJSaGJHVWdVM1FnVFdWc1lnQUFBQUFBJCQk',
    expectedFields: [
      ['id', 'Melbourne Central, Kiosk 2, Ground Floor  300 Lonsdale Street, MELBOURNE  VIC 3000, Australia'],
      ['alt_key', ''],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730VOAUEHALnBwAAAAAIAgEAAAACWyJAkBghAQIQCCAAAAAAAAAAAP..ZAAAAAD.....AAAAAAAAAAAAAAAAAAAATG9uc2RhbGUgU3QgTWVsYgAAAAAA$$$'],
    ],
    expectedAltKey: null,
  },
  // Addresses with 1 part.
  {
    address: '1-3 Pitt Street, BADGERYS CREEK  NSW 2555',
    globalAddressKey: 'aWQ9MS0zIFBpdHQgU3RyZWV0LCBCQURHRVJZUyBDUkVFSyAgTlNXIDI1NTUsIEF1c3RyYWxpYX5hbHRfa2V5PX5kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzBvT0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBRkZSSFVBQWdBQUFBQUFBQUFBRC4uMFlBQUFBQS4uLi4ud0FBQUFBQUFBQUFBQUFBQUFBQUFESWdVR2wwZENCVGVXUUFBQUFBQUEtLSQkJA',
    expectedFields: [
      ['id', '1-3 Pitt Street, BADGERYS CREEK  NSW 2555, Australia'],
      ['alt_key', ''],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730oOAUEHALnBwAAAAAIAgEAAAAAFFRHUAAgAAAAAAAAAAD..0YAAAAA.....wAAAAAAAAAAAAAAAAAAADIgUGl0dCBTeWQAAAAAAA--$$$'],
    ],
    expectedAltKey: null,
  },
  {
    address: 'Unit 1  97 Bondi Road, BONDI  NSW 2026',
    globalAddressKey: 'aWQ9VW5pdCAxICA5NyBCb25kaSBSb2FkLCBCT05ESSAgTlNXIDIwMjYsIEF1c3RyYWxpYX5hbHRfa2V5PX5kYXRhc2V0PUFVU19EQVRBRlVTSU9OfmZvcm1hdF9rZXk9QVVTJGRhdGFmdXNpb24kNy43MzBIT0FVRUhBTG5Cd0FBQUFBSUFnRUFBQUFBSThBbjBCZ2hBUUlRQ0NFQUFnQUFBQUFBQUFBQUFQLi5QQUFBQUFELi4uLi5BQUFBQUFBQUFBQUFBQUFBQUFBQVFtOXVaR2tnVW1RZ1UzbGtBQUFBQUFBLSQkJA',
    expectedFields: [
      ['id', 'Unit 1  97 Bondi Road, BONDI  NSW 2026, Australia'],
      ['alt_key', ''],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730HOAUEHALnBwAAAAAIAgEAAAAAI8An0BghAQIQCCEAAgAAAAAAAAAAAP..PAAAAAD.....AAAAAAAAAAAAAAAAAAAAQm9uZGkgUmQgU3lkAAAAAAA-$$$'],
    ],
    expectedAltKey: null,
  },
  // Addresses with 3 parts.
  {
    address: 'Shop 1  109 Bondi Road, BONDI  NSW 2026',
    globalAddressKey: 'aWQ9U2hvcCAxICAxMDkgQm9uZGkgUm9hZCwgQk9OREkgIE5TVyAyMDI2LCBBdXN0cmFsaWF-YWx0X2tleT1-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwWU9BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQUk4QXNVQmdoQVFJUUNDRUFBZ0FBQUFBQUFBQUFBUC4uUEFBQUFBRC4uLi4uQUFBQUFBQUFBQUFBQUFBQUFBQUFRbTl1WkdrZ1VtUWdVM2xrQUFBQUFBQS0kJCQ',
    expectedFields: [
      ['id', 'Shop 1  109 Bondi Road, BONDI  NSW 2026, Australia'],
      ['alt_key', ''],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730YOAUEHALnBwAAAAAIAgEAAAAAI8AsUBghAQIQCCEAAgAAAAAAAAAAAP..PAAAAAD.....AAAAAAAAAAAAAAAAAAAAQm9uZGkgUmQgU3lkAAAAAAA-$$$'],
    ],
    expectedAltKey: null,
  },
  {
    address: 'Shop 1, Ground Floor  18-20 York Street, SYDNEY  NSW 2000',
    globalAddressKey: 'aWQ9U2hvcCAxLCBHcm91bmQgRmxvb3IgIDE4LTIwIFlvcmsgU3RyZWV0LCBTWURORVkgIE5TVyAyMDAwLCBBdXN0cmFsaWF-YWx0X2tleT1-ZGF0YXNldD1BVVNfREFUQUZVU0lPTn5mb3JtYXRfa2V5PUFVUyRkYXRhZnVzaW9uJDcuNzMwQk9BVUVIQUxuQndBQUFBQUlBZ0VBQUFBQXladUkwQmdoQVFJUUNDRUFBZ0FBQUFBQUFBQUFBUC4uU3dBQUFBRC4uLi4uQUFBQUFBQUFBQUFBQUFBQUFBQUFOeTh4T0NCWmIzSnJJRk4wSUZONVpBQUFBQUFBJCQk',
    expectedFields: [
      ['id', 'Shop 1, Ground Floor  18-20 York Street, SYDNEY  NSW 2000, Australia'],
      ['alt_key', ''],
      ['dataset', 'AUS_DATAFUSION'],
      ['format_key', 'AUS$datafusion$7.730BOAUEHALnBwAAAAAIAgEAAAAAyZuI0BghAQIQCCEAAgAAAAAAAAAAAP..SwAAAAD.....AAAAAAAAAAAAAAAAAAAANy8xOCBZb3JrIFN0IFN5ZAAAAAAA$$$'],
    ],
    expectedAltKey: null,
  },
];

describe('iterateGlobalAddresskeyFields()', () => {
  it('handles empty string', () => {
    const generator = iterateGlobalAddresskeyFields('');
    const actual = Array.from(generator);
    expect(actual).toEqual([]);
  });

  test.each(cases)('handles "$address"', ({ globalAddressKey, expectedFields }) => {
    const generator = iterateGlobalAddresskeyFields(globalAddressKey);
    const actual = Array.from(generator);
    expect(actual).toEqual(expectedFields);
  });
});

describe('getAltKey()', () => {
  it('handles empty string', () => {
    const actual = getAltKey('');
    expect(actual).toBeNull();
  });

  test.each(cases)('handles "$address"', ({ globalAddressKey, expectedAltKey }) => {
    const actual = getAltKey(globalAddressKey);
    expect(actual).toBe(expectedAltKey);
  });
});
